### ISSUE TITLE
token validation fail

### ISSUE THREAD

**Issue by giuleon** [estruyf/SharePoint-Webhook-Node-Sample#1]
Hi @estruyf,

after that I clicked on create a new subscription I receive from SharePoint this:
{"error":{"code":"-1, System.InvalidOperationException","message":{"lang":"en-US","value":"Failed to validate the notification URL 'https://ae8ea27f.ngrok.io'."}}}

**Comment by estruyf** [comment]
Do you have ngrok running on your machine? Do you see any request coming in? If not, it could be related to the ngrok connection.

**Comment by giuleon** [comment]
I think that I have an ngrok connection problem, I'll go deep, eventually can I deploy as is this solution on Azure App Service NodeJS right or must I have to do some configurations ?

**Comment by estruyf** [comment]
Not yet tested, but it should work if you pass in the right config settings.

**Comment by giuleon** [comment]
ok I'll try, thank you @estruyf

**Comment by giuleon** [comment]
Hi,

I deployed the solution on Azure but I receive "You do not have permission to view this directory or page" when I try to display the page, now I'm not an expert of nodejs but I think that is necessary the web.config and server.js files in the application root, is that right ?

**Comment by estruyf** [comment]
Depends on how you publish the files to Azure. If you do it manually, you would have to create a web.config file. This is what mine looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<!--
     This configuration file is required if iisnode is used to run node processes behind
     IIS or IIS Express.  For more information, visit:

     https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config
-->

<configuration>
  <system.webServer>
    <!-- Visit http://blogs.msdn.com/b/windowsazure/archive/2013/11/14/introduction-to-websockets-on-windows-azure-web-sites.aspx for more information on WebSocket support -->
    <webSocket enabled="false" />
    <handlers>
      <add name="iisnode" path="src/index.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        <!-- Do not interfere with requests for node-inspector debugging -->
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^src/index.js\/debug[\/]?" />
        </rule>

        <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        <!-- All other URLs are mapped to the node.js site entry point -->
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="src/index.js"/>
        </rule>
      </rules>
    </rewrite>
    
    <!-- 'bin' directory has no special meaning in node.js and apps can be placed in it -->
    <security>
      <requestFiltering>
        <hiddenSegments>
          <remove segment="bin"/>
        </hiddenSegments>
      </requestFiltering>
    </security>

    <!-- Make sure error responses are left untouched -->
    <httpErrors existingResponse="PassThrough" />

    <!--
      You can control how Node is hosted within IIS using the following options:
        * watchedFiles: semi-colon separated list of files that will be watched for changes to restart the server
        * node_env: will be propagated to node as NODE_ENV environment variable
        * debuggingEnabled - controls whether the built-in debugger is enabled

      See https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config for a full list of options
    -->
    <!--<iisnode watchedFiles="web.config;*.js"/>-->
  </system.webServer>
</configuration>
```

Another thing I noticed is that you have to change the `privatekey.pem` path in the `/src/helpers/TokenHelper.js` file. Line 4 should be:

```
var certificate = fs.readFileSync('../privatekey.pem', { encoding: 'utf8' });
```

After this change, it should work.

**Comment by giuleon** [comment]
About the deploy I used Azure CLI and Visual Studio Code for nodejs azure app I followed this procedure (only to create the site by command line):
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-nodejs-get-started

but unfortunately I have an http error 404

*I used your web.config (for you every things works on Azure ?)

**Comment by estruyf** [comment]
One thing I forgot to mention, as it was created for local use only, you have to change the `scripts` object in the `package.json` file:

```json
"scripts": {
    "start": "node ./src/index.js",
    "debug": "gulp typescript & node ./src/index.js"
  }
```

As you are deploying it via git, you will also have to change some things in the `.gitignore` file. This is causing the 404, because it is not pushing the JS files, only the TS files to Azure. The only thing you need in that file is:

```
node_modules
typings
local-settings
*.log
```

**Comment by giuleon** [comment]
Thanks now works even on Azure but when I click on create I receive ever "Failed to validate the notification URL", I tried to log the validationToken that I receive from SharePoint on "webhooks.txt" but nothing.
I used postman to check if the nodejs app return the validationtoken in the body and in plain text as should work but I receive "Cannot POST /?validationtoken=..........." look the attachments.
<img width="709" alt="noheaders" src="https://cloud.githubusercontent.com/assets/3914090/21083613/5ca81800-bff4-11e6-9aa1-e3008247abf9.PNG">
<img width="1078" alt="validationtoken" src="https://cloud.githubusercontent.com/assets/3914090/21083612/5ca6f088-bff4-11e6-9959-04c6a9a2b947.PNG">


* I configured CORS properly for the web app

**Comment by estruyf** [comment]
Validation is done on the `/listen` endpoint. Have you setup the correct URLs in the config.json file? When you do a change in the file, you will also have to restart the site.

**Comment by giuleon** [comment]
That's my config file:
`{
    "adalConfig": {
        "authority": "https://login.microsoftonline.com/<MyTenant>.onmicrosoft.com",
        "clientID": "My client id",
        "subscriptionUrl": "https://nodejswebhooks.azurewebsites.net",
        "resource": "https://<MyTenant>.sharepoint.com",
        "fingerPrint": "My finger print"
    },
    "webhookConfig": {
        "url": "https://<MyTenant>.sharepoint.com/sites/web-hooks",
        "listName": "webhook",
        "clientState": "my client state"
    }
}`
then if it is so, I need to modify the subscriptionUrl -> "https://nodejswebhooks.azurewebsites.net/listen"

**Comment by estruyf** [comment]
Yes, that would be correct (the one with listen).

**Comment by giuleon** [comment]
Now I have the following error:
![tasks1](https://cloud.githubusercontent.com/assets/3914090/21097764/776e187a-c066-11e6-8e41-bba107cc63eb.png)

My Azure Active Directory Application is configured well:
![tasks2](https://cloud.githubusercontent.com/assets/3914090/21097799/98d94610-c066-11e6-85d1-60429a4e4852.png)

Maybe this error It's caused by the manifest file or from my certificate file .pem ?

**Comment by giuleon** [comment]
After a check in the file manifest I have seen that the value of keyCredentials is null, but if I try to re-add this value I have the following error:
![tasks3](https://cloud.githubusercontent.com/assets/3914090/21098528/ec6cd672-c069-11e6-8f40-bff7cca0676f.png)

**Comment by giuleon** [comment]
I solved there was a wrong value for the "identifierUris" into the manifest. thank you for your support,
I'm available if you want, obviously, to collaborate with you for this or other solutions. ;-)

**Comment by giuleon** [comment]
I forgot, only for your info, obviously I changed the static url into the index,html file "http://localhost:3000" in favor of window.location.origin

**Comment by estruyf** [comment]
Thanks for the feedback, glad it worked out!
